include required("/stdlib/jdk/21/amazon.conf")

app {
  display-name = "Coffee Recipes"
  rdns-name = "com.cait.coffeerecipe"
  version = "1.0.0"

  site {
    github {
      oauth-token = ${env.GITHUB_TOKEN}
      pages-branch = "gh-pages"
    }
  }

  jvm {
    gui {
      main-class = "main.Open"
    }
  }

  inputs += "target/*.jar"
  inputs += "target/dependency/*.jar"
}