include required("/stdlib/jdk/21/amazon.conf")

conveyor.billing-email = "cait.hope.fern@gmail.com"

app {
  display-name = "Coffee Recipe"
  rdns-name = "com.cait.coffeerecipe"
  version = "1.0.2"

  site {
    base-url = "https://caitisaloser.github.io/CoffeeRecipe"
    
    github {
      oauth-token = ${env.GITHUB_TOKEN}
      pages-branch = "gh-pages"
    }
  }

  jvm {
    gui {
      main-class = "main.Open" 
    }
  }

  inputs += "target/*.jar"
  inputs += "target/dependency/*.jar"
}